[package]
name = "custom-derive"
version = "0.1.0"
authors = ["Tony Huang <cnwzhjs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ui = { path = "../ui" }
ui_macro = { path = "../ui-macro" }
